---
# Default values for microservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  replicaCount: 1
  environment:
   # list of key: value
   # GLOBAL1: value

## Set default image, imageTag, and imagePullPolicy.
## ref: https://hub.docker.com/r/apache/nifi/
##


image: damilare77/auth
imageConfig:
  repository:
  tag: "latest"
  pullPolicy: IfNotPresent

#command: ['echo pre-install Job Pod is Running']

replicaCount: 1

# command: ["/bin/sh","-c"]
# args: ["echo 'consuming a message'; sleep 5"]

nameOverride: deployment
fullnameOverride: ""

# Annotation for the Deployment
annotations: {}


# List of services
services:
  - name: web
    type: ClusterIP
    annotations: {}
    specs:
      - port: 3000
        targetPort: 3000
        name: port-svc

environment:
  - name: MONGO_URI
    valueFrom:
      configMapKeyRef:
        name: auth-mongo-configmap
        key: database_url
  - name: JWT_KEY
    valueFrom:
      secretKeyRef:
        name: jwt-secret
        key: JWT_KEY


dbConfigMap: false
eventConfigMap: false
redisConfigMap: false

ingress:
  enabled: false

volumes:
  enabled: false
  pvc:
    enabled: false
    existing_claim:
    name: pvc
    mountPath: /pv
    size: 1G
    class:
    accessModes:
      - ReadWriteOnce



resources:
  limits:
    cpu: 2
    memory: 2000Mi
  requests:
    cpu: 500m
    memory: 500Mi