apiVersion: networking.k8s.io/v1beta1
kind: Ingress #kind of object
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx #create ingress controller based on nginx project
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-cluster-ip-service
              servicePort: 3000
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-cluster-ip-service
              servicePort: 3000
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-cluster-ip-service
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
