apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: damilare77/orders
          ports:
            - containerPort: 3000
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name #pod name
            - name: NATS_URL
              value: "http://nats-cluster-ip-service:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: mongodb://orders-mongo-cluster-ip-service:27017/orders
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: orders-cluster-ip-service
spec: #actual configuration the way the service behaves
  type: ClusterIP
  ports: #ports that the clusterIP will expose or be available on
    - name: event-bus
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: orders
