apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-mongo
  template:
    metadata:
      labels:
        app: payments-mongo
    spec:
      containers:
        - name: payments-mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: payments-mongo-cluster-ip-service
spec: #actual configuration the way the service behaves
  type: ClusterIP
  ports: #ports that the clusterIP will expose or be available on
    - name: payments
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: payments-mongo
