  
name: deploy-manifest

on:
  push:
    branches: 
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2 #install doctl
        with: #credentials
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 
      - run: doctl kubernetes cluster kubeconfig save k8s-ticketing #connect to k8s cluster
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
