name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t damilare77/client . #build image
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD #login to docker
        env: #credentials
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push damilare77/client #push to docker
      - uses: digitalocean/action-doctl@v2 #install doctl
        with: #credentials
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-ticketing #connect to k8s cluster
      - run: kubectl rollout restart deployment client-depl #restart depl with latest docker image